# OuterClothing
- type: loadout
  id: ClothingHOSWinterJacket
  equipment:
    outerClothing: ClothingOuterCoatHOSWinterCoat

# Jumpsuits / Jumpskirts
- type: loadout
  id: HoSParadeUniformMale
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSParadeMale

- type: loadout
  id: HoSParadeUniformFemale
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSParadeMale


#Belt
- type: loadout
  id: HosSwordBelt
  effects:
  - !type:GroupLoadoutEffect
    proto: SeniorOfficer
  equipment:
    belt: ClothingBeltSheathStunswordFilled